# For documentation on how to configure this file,
# see diesel.rs/guides/configuring-diesel-cli

[print_schema]
file = "src/schema/db.rs"
with_docs = true

# Add support for Citext
import_types = [
  # Ugly hack for allowing unused imports but it works
  "diesel::sql_types::*;\n#[allow(unused_imports)]//",
  "diesel_citext::sql_types::*"
]